import { useEffect, useRef, useState } from 'react'
import { motion, useScroll, useTransform } from 'framer-motion'
import Lenis from 'lenis'
import { ArrowUpRight, Check, Clock, Shield, BadgeCheck, Gauge, Zap, Code2 } from 'lucide-react'

function useSmoothScroll() { useEffect(() => { const lenis = new Lenis({ duration: 1.2, smoothWheel: true }); function loop(t) { lenis.raf(t * 1000); requestAnimationFrame(loop) } requestAnimationFrame(loop); if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) lenis.stop(); return () => lenis.destroy() }, []) }
const SplitWords = ({ text, className = '' }) => { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start 88%', 'end 60%'] }); const words = text.split(' '); const ys = words.map((w, i) => useTransform(scrollYProgress, [i / words.length, (i + 1.2) / words.length], ['120%', '0%'], { clamp: true })); return <h2 ref={ref} className={className} style={{ margin: 0 }}>{words.map((w, i) => <span key={i} className="wm" style={{ display: 'inline-block', overflow: 'hidden', paddingBottom: '.12em' }} aria-hidden="true"><motion.span style={{ y: ys[i], display: 'inline-block' }}>{w}</motion.span>{'\u00A0'}</span>)}</h2> }
const Reveal = ({ children, delay = 0 }) => { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start 88%', 'end 65%'] }); const y = useTransform(scrollYProgress, [0, 1], [48, 0]); const o = useTransform(scrollYProgress, [0, .35], [0, 1]); return <motion.div ref={ref} style={{ y, opacity: o }}>{children}</motion.div> }
const Magnetic = ({ children, strength = .3 }) => { const ref = useRef(null); return <motion.div ref={ref} onMouseMove={(e) => { const el = ref.current, r = el.getBoundingClientRect(); el.style.transform = `translate(${(e.clientX - (r.left + r.width / 2)) * strength}px, ${(e.clientY - (r.top + r.height / 2)) * strength}px)` }} onMouseLeave={() => { ref.current.style.transform = 'translate(0,0)' }} style={{ transition: 'transform .4s cubic-bezier(.22,1,.36,1)', display: 'inline-block' }}>{children}</motion.div> }

const Header = () => <header className="site-header"><div className="header-inner"><a href="#" className="logo">Rise<span>.</span></a><nav><a href="#services">Services</a><a href="#results">Results</a><a href="#pricing">Pricing</a><a href="#process">Process</a><Magnetic><motion.a href="#contact" whileHover={{ scale: 1.05 }} className="btn-cta">Start a project</motion.a></Magnetic></nav></div></header>
const Hero = () => { const ref = useRef(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] }); const y = useTransform(scrollYProgress, [0, 1], ['0%', '22%']); const o = useTransform(scrollYProgress, [0, .5], [1, 0]); return <section ref={ref} className="hero rise-hero"><motion.div className="hero-inner" style={{ y, opacity: o }}><p className="kicker">Kinetic type studio — every word earns its entrance</p><h1><motion.span className="hw" initial={{ opacity: 0, y: 90 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9, ease: [0.16,1,0.3,1], delay: .3 }}>Words that</motion.span> <motion.span className="hw accent" initial={{ opacity: 0, y: 90 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9, ease: [0.16,1,0.3,1], delay: .44 }}>rise.</motion.span></h1><motion.p className="hero-sub" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .78 }}>Headlines rise out of clipped masks, split word by word as you scroll. Kinetic typography that turns a sentence into a moment.</motion.p><motion.div className="hero-ctas" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .92 }}><Magnetic><motion.a href="#contact" whileHover={{ scale: 1.06 }} className="btn-primary">Get a free quote <ArrowUpRight size={16} style={{ verticalAlign: 'middle', marginLeft: 4 }} /></motion.a></Magnetic><Magnetic><motion.a href="#pricing" whileHover={{ scale: 1.06 }} className="btn-ghost">See pricing</motion.a></Magnetic></motion.div></motion.div></section> }
const Stack = () => { const stack = ['SplitType', 'GSAP', 'React', 'variable fonts', 'framer-motion', 'TypeScript', 'Vite']; const metrics = [{ icon: <Gauge size={18} />, n: '60fps', l: 'Type reveals' }, { icon: <Zap size={18} />, n: '0.7s', l: 'Avg load' }, { icon: <Code2 size={18} />, n: '100', l: 'Core Web Vitals' }, { icon: <BadgeCheck size={18} />, n: 'AA', l: 'Accessible' }]; return <section className="stackband"><div className="wrap"><Reveal><p className="stack-label">Typographic motion, performance-first</p></Reveal><Reveal delay={.08}><div className="stack-row">{stack.map(s => <span key={s}>{s}</span>)}</div></Reveal><div className="tech-grid">{metrics.map((m, i) => <Reveal key={i} delay={i * .06}><div className="tech-metric">{m.icon}<div><b>{m.n}</b><span>{m.l}</span></div></div></Reveal>)}</div></div></section> }
const RESULTS = [{ n: '+140%', l: 'Headline attention', tag: 'kinetic type stops scrolling' }, { n: '+25%', l: 'Message recall', tag: 'words are remembered' }, { n: '70+', l: 'Kinetic sites shipped', tag: 'brand editorial' }, { n: '-28%', l: 'Bounce rate', tag: 'people read to the end' }]
const Results = () => <section className="results" id="results"><div className="wrap"><Reveal><SplitWords text="Type that makes you stop." className="sec-title" /></Reveal><p className="sec-sub">A rising word is worth a hundred static ones. Kinetic type keeps people reading.</p><div className="results-grid">{RESULTS.map((r, i) => <Reveal key={i} delay={i * .08}><div className="result-card"><div className="result-n">{r.n}</div><div className="result-l">{r.l}</div><div className="result-tag">{r.tag}</div></div></Reveal>)}</div></div></section>
const SERVICES = [{ icon: '01', title: 'Launch headlines', desc: 'Every new product gets an entrance worth the wait.', price: 'from €800', time: '1 wk' }, { icon: '02', title: 'Editorial type', desc: 'Longform sites where section titles rise into view.', price: 'from €3,400', time: '2-3 wks' }, { icon: '03', title: 'Brand manifestos', desc: 'Values told one weighted, rising word at a time.', price: 'from €1,900', time: '1-2 wks' }, { icon: '04', title: 'Full kinetic sites', desc: 'Complete React builds with kinetic type throughout.', price: 'from €4,700', time: '3-4 wks' }]
const Services = () => <section className="services" id="services"><div className="wrap"><Reveal><SplitWords text="What we build." className="sec-title" /></Reveal><div className="svc-grid">{SERVICES.map((s, i) => <Reveal key={i} delay={i * .08}><motion.div className="service-card" whileHover={{ y: -8, transition: { type: 'spring', stiffness: 300 } }}><div className="num">{s.icon}</div><h3>{s.title}</h3><p>{s.desc}</p><div className="svc-meta"><span className="price">{s.price}</span><span className="time"><Clock size={13} /> {s.time}</span></div><a href="#contact" className="svc-link">Start this →</a></motion.div></Reveal>)}</div></div></section>
const PLANS = [{ name: 'Headline', price: '€800', for: 'One hero reveal', feats: ['1 kinetic headline', '2 revisions', 'Optimised reveal', '1 week delivery'] }, { name: 'Manifesto', price: '€4,700', for: 'Full kinetic site', feats: ['Multi-section kinetic type', 'Variable font system', 'Contact / CTA', '3 revision rounds', 'Performance report', '30 days support'] }, { name: 'Editorial', price: '€8,500', for: 'Award-level typography', feats: ['Everything in Manifesto', 'Custom split + scrub', 'A/B ready', '90 days support'] }]
const Pricing = () => { const [sel, setSel] = useState(1); return <section className="pricing" id="pricing"><div className="wrap"><Reveal><SplitWords text="Clear type pricing." className="sec-title" /></Reveal><div className="plan-grid">{PLANS.map((p, i) => <Reveal key={i} delay={i * .08}><motion.div className={`plan ${i === sel ? 'plan-feat' : ''}`} whileHover={{ y: -6 }} onClick={() => setSel(i)}>{i === sel && <span className="plan-pop">Most chosen</span>}<h3>{p.name}</h3><div className="plan-price">{p.price}</div><div className="plan-for">{p.for}</div><ul>{p.feats.map((f, k) => <li key={k}><Check size={15} /> {f}</li>)}</ul><motion.a href="#contact" className="plan-btn" whileHover={{ scale: 1.04 }}>Choose {p.name}</motion.a></motion.div></Reveal>)}</div><Reveal><div className="guarantee"><Shield size={18} /> Every build ships with a <b>written delivery date</b> and <b>30-day support</b>.</div></Reveal></div></section> }
const PROCESS = [{ n: '01', t: 'Copy & rhythm', d: 'We tighten your words and plan the reveal rhythm.', icon: '✍️' }, { n: '02', t: 'Type direction', d: 'Variable font system and visual route.', icon: '🔤' }, { n: '03', t: 'Build', d: 'Split + scroll reveals in React, sprint by sprint.', icon: '⚙️' }, { n: '04', t: 'Launch', d: 'Ship, measure attention, refine.', icon: '🚀' }]
const Process = () => <section className="process" id="process"><div className="wrap"><Reveal><SplitWords text="Built word by word." className="sec-title" /></Reveal><div className="proc-grid">{PROCESS.map((p, i) => <Reveal key={i} delay={i * .08}><motion.div className="proc-step" whileHover={{ y: -6 }}><div className="proc-num">{p.n}<span>{p.icon}</span></div><h4>{p.t}</h4><p>{p.d}</p></motion.div></Reveal>)}</div></div></section>
const QUOTES = [{ q: "Rise's headline reveal got more mentions than the actual product launch. Pure theater.", n: 'Nina K.', r: 'CMO, Prisma' }, { q: "Our about page now reads like a film because every word rises into view.", n: 'Tom B.', r: 'Founder, Fieldnote' }, { q: "Delivered kinetic type at 60fps, on budget, on time.", n: 'Sofia R.', r: 'Brand lead, Bellwether' }]
const Testimonials = () => <section className="quotes"><div className="wrap"><Reveal><SplitWords text="Clients who read to the end." className="sec-title" /></Reveal><div className="quotes-grid">{QUOTES.map((q, i) => <Reveal key={i} delay={i * .08}><figure className="quote"><div className="stars">★★★★★</div><blockquote>{q.q}</blockquote><figcaption><b>{q.n}</b><span>{q.r}</span></figcaption></figure></Reveal>)}</div></div></section>
const CTA = () => { const [sent, setSent] = useState(false); return <section className="cta" id="contact"><div className="wrap cta-inner"><Reveal><SplitWords text="Make your words rise." className="sec-title" /></Reveal><p className="sec-sub">Tell us about your project — a motion plan and fixed quote within one business day.</p>{!sent ? <motion.form className="cta-form" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} onSubmit={(e) => { e.preventDefault(); setSent(true) }}><div className="form-row"><input required placeholder="Your name" aria-label="Your name" /><input required type="email" placeholder="Work email" aria-label="Work email" /></div><textarea rows="3" placeholder="Tell us about your message & where kinetic type helps" aria-label="Project details" /><Magnetic><motion.button whileHover={{ scale: 1.05 }} className="btn-primary" type="submit" style={{ border: 'none', cursor: 'pointer' }}>Send project brief <ArrowUpRight size={16} style={{ verticalAlign: 'middle', marginLeft: 4 }} /></motion.button></Magnetic><p className="form-note"><Shield size={13} /> Free quote · no obligation · reply within 1 business day</p></motion.form> : <motion.div className="cta-done" initial={{ scale: 0.8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}><BadgeCheck size={44} /><h3>Brief received 🎉</h3><p>We'll reply within one business day.</p></motion.div>}<div className="cta-contact"><span>Prefer email?</span> <a href="mailto:studio@rise.type">studio@rise.type</a></div></div></section> }
const Footer = () => <footer className="site-footer"><div className="wrap foot-inner"><span>© 2026 Rise — kinetic type.</span><span><a href="#services">Services</a> · <a href="#pricing">Pricing</a> · <a href="mailto:studio@rise.type">studio@rise.type</a></span></div></footer>

export default function App() {
  useSmoothScroll()
  return (<><Header /><Hero /><Stack /><Results /><Services /><Pricing /><Process /><Testimonials /><CTA /><Footer /></>)
}
